name: Update deps
on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.9.3
      - name: Update dependencies
        run: pnpm up -L
      - uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: 'Update dependencies'
